### ISSUE TITLE
when installing with npm, dependency crafity-config cannot be found

### ISSUE THREAD

**Issue by rewop** [Crafity/crafity-webserver#2]
When updating the crafity-webserver module for Konnektid project, the install fails when trying to install the dependency crafity-config:

npm install crafity-webserver
npm http GET https://registry.npmjs.org/crafity-webserver
npm http 304 https://registry.npmjs.org/crafity-webserver
npm http GET https://registry.npmjs.org/crafity-core
npm http GET https://registry.npmjs.org/crafity-filesystem
npm http GET https://registry.npmjs.org/crafity-jstest
npm http GET https://registry.npmjs.org/crafity-resources
npm http GET https://registry.npmjs.org/connect-assetmanager
npm http GET https://registry.npmjs.org/crafity-logging
npm http GET https://registry.npmjs.org/crafity-gzip
npm http GET https://registry.npmjs.org/connect-redis
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/http-proxy
npm http GET https://registry.npmjs.org/jade
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/nib
npm http GET https://registry.npmjs.org/redis
npm http GET https://registry.npmjs.org/stylus
npm http GET https://registry.npmjs.org/validator
npm http GET https://registry.npmjs.org/util
npm http GET https://registry.npmjs.org/url
npm http GET https://registry.npmjs.org/crafity-everyauth
npm http GET https://registry.npmjs.org/crafity-config
npm http 304 https://registry.npmjs.org/crafity-core
npm http 304 https://registry.npmjs.org/crafity-jstest
npm http 304 https://registry.npmjs.org/crafity-resources
npm http 304 https://registry.npmjs.org/connect-assetmanager
npm http 304 https://registry.npmjs.org/crafity-filesystem
npm http 304 https://registry.npmjs.org/crafity-logging
npm http 304 https://registry.npmjs.org/crafity-gzip
npm http 304 https://registry.npmjs.org/connect-redis
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/http-proxy
npm http 304 https://registry.npmjs.org/jade
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/nib
npm http 304 https://registry.npmjs.org/redis
npm http 304 https://registry.npmjs.org/stylus
npm http 304 https://registry.npmjs.org/validator
npm http 304 https://registry.npmjs.org/util
npm http 304 https://registry.npmjs.org/url
npm http 304 https://registry.npmjs.org/crafity-everyauth
npm http 304 https://registry.npmjs.org/crafity-config
npm http GET https://registry.npmjs.org/crafity-config/-/crafity-config-0.1.2.tgz
npm http 404 https://registry.npmjs.org/crafity-config/-/crafity-config-0.1.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/crafity-config/-/crafity-config-0.1.2.tgz
unbuild crafity-webserver@0.1.2
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 12.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "crafity-webserver"
npm ERR! cwd /Users/simonepotenza/Development/node/apps/Konnektid
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/simonepotenza/Development/node/apps/Konnektid/npm-debug.log
npm ERR! not ok code 0

Can you help with this?

**Comment by briemens** [comment]
Seems to be an issue with NPM. The module crafity-config was not published correctly.

This is fixed with issue https://github.com/Crafity/crafity-config/issues/3
